version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo "Deploy Beginning for ${BRANCH_NAME} branch"
      - aws s3 sync build/ "s3://${BUCKET_NAME}" --delete
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "Build/Deploy success"    
        else
          echo "Build/Deploy failure"    
        fi
